### ISSUE TITLE
Fix Hero block layout toolbar control

### ISSUE THREAD

**Issue by richtabor** [godaddy/coblocks#780] opened 2019-08-27 00:54 UTC
**Describe the bug**
The Hero Block's Layout toolbar control is not properly displaying (Safari/Chrome MacOS). When submitting the PR for this, we'll need to ensure this also displays properly on FF and IE. 

**Screenshots**
Default: 
<img width="729" alt="Screen Shot 2019-08-26 at 8 48 17 PM" src="https://user-images.githubusercontent.com/1813435/63732685-65ee7080-c843-11e9-884c-aeb0da536769.png">

When Fullscreen is toggled: 
<img width="281" alt="Screen Shot 2019-08-26 at 8 50 57 PM" src="https://user-images.githubusercontent.com/1813435/63732677-5c650880-c843-11e9-80fa-0375612e100a.png">

**Expected behavior**
Control displays properly as such: 
<img width="261" alt="Screen Shot 2019-08-26 at 8 50 33 PM" src="https://user-images.githubusercontent.com/1813435/63732640-2fb0f100-c843-11e9-8e71-97ead23d5a75.png">
<img width="257" alt="Screen Shot 2019-08-26 at 8 51 16 PM" src="https://user-images.githubusercontent.com/1813435/63732671-58d18180-c843-11e9-9b3a-f28bffc05599.png">

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using? 5.2.2

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
Happens with and without Gutenberg activated.

**Comment by jrtashjian** [comment] 2019-08-29 22:42
Looks like a regression because this was fixed in #680.

**Comment by richtabor** [comment] 2019-08-30 14:26
> Looks like a regression because this was fixed in #680.

With Gutenberg, or something that was merged in?

**Comment by paranoia1906** [comment] 2019-09-01 19:05
Looks like the regression came in-between release of 1.12.0 and 1.12.1.
When running 1.12.0 downloaded from GitHub the issues does **not** occur.
When running 1.12.1 downloaded from GitHub the issues **occurs**.

**Running 1.12.0**
![image](https://user-images.githubusercontent.com/30462574/64081039-7d4cb400-ccb0-11e9-8341-454fbe1e6395.png)

**Running 1.12.1**
![image](https://user-images.githubusercontent.com/30462574/64081048-92c1de00-ccb0-11e9-8e64-8ea78b7f9b89.png)

Have not yet identified the cause of the regression. Here is compare between commits for 1.12.0 > 1.12.1
https://github.com/godaddy/coblocks/compare/1165244...bbe00f2

**Closed** 2019-09-04 20:09 UTC
Labels: [Block] Hero, bug, gutenberg plugin
